name: FactionsPlus
author: FactionsPlus devs
main: FactionsMain.php
api: 2.0.0
version: 1.0
commands:
 f:
  permission: factions.command
  description: FactionsPlus Command
  usage: /f [help]
permissions:
    factions.command:
      default: true
      description: FactionsPlus command
